name: Scan topic

on:
  workflow_dispatch:
  #schedule:
    #- cron: "0 0 * * *"

env:
  DETA_KEY: ${{ secrets.DETA_KEY }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: |
        yarn
        yarn build
        yarn start
        curl "http://localhost:3000/api/rescan"
